feature/gh-37-secondary-app
- Add flag --secondary.
  If it's set, the app won't be a "main" app (example.com or
  www.example.com), but rather, a "secondary" app (for example
  redmine.example.com), which can run alongside a main app.

diff --git a/bin/dokku-scrubs b/bin/dokku-scrubs
--- a/bin/dokku-scrubs
+++ b/bin/dokku-scrubs
@@ -12,6 +12,7 @@ source "$LIB_DIR/common.sh"
 source "$LIB_DIR/init.sh"
 source "$LIB_DIR/db.sh"
 source "$LIB_DIR/app.sh"
+source "$LIB_DIR/domains.sh"
 source "$LIB_DIR/letsencrypt.sh"
 source "$LIB_DIR/post-deploy.sh"
 source "$LIB_DIR/shflags"
@@ -25,6 +26,7 @@ DEFINE_string  "database"     "" "the type of database to use, leave blank to us
 DEFINE_string  "email"        "" "email address for letsencrypt" "e"
 DEFINE_boolean "letsencrypt"  false "pass this flag to enable SSL" "l"
 DEFINE_boolean "testcert"     false "pass this flag along with --letsencrypt, to get certs from the staging server" "T"
+DEFINE_boolean "secondary"    false "install as a secondary app on a subdomain"
 
 DEFINE_boolean "version" false "show version and exit" "v"
 
@@ -49,6 +51,11 @@ if [[ ${FLAGS_letsencrypt} -eq ${FLAGS_TRUE} && -z "${FLAGS_email}" ]]; then
   exit 1
 fi
 
+if [[ ${FLAGS_wwwsubdomain} -eq ${FLAGS_TRUE} && ${FLAGS_secondary} -eq ${FLAGS_TRUE} ]]; then
+  log "--wwwsubdomain cannot be used with --secondary"
+  exit 1
+fi
+
 if [[ -z "${FLAGS_database}" ]]; then
   database="${APP_DB[${FLAGS_app}]}"
 else
@@ -58,11 +65,13 @@ fi
 domain="${FLAGS_domain#www.}"
 
 init_system "${FLAGS_app}"
-init_dokku "$domain" "${FLAGS_wwwsubdomain}" "${FLAGS_dokkutag}" "$database"
+init_dokku "$domain" "${FLAGS_wwwsubdomain}" "${FLAGS_secondary}" \
+  "${FLAGS_dokkutag}" "$database"
 create_app "${FLAGS_app}"
 setup_db "$database" "${FLAGS_app}"
 mount_volumes "${FLAGS_app}" "${FLAGS_appversion}"
-deploy_app "${FLAGS_app}" "$domain" "${FLAGS_wwwsubdomain}" "${FLAGS_appversion}"
+deploy_app "${FLAGS_app}" "$domain" \
+  "${FLAGS_wwwsubdomain}" "${FLAGS_secondary}" "${FLAGS_appversion}"
 map_port "${FLAGS_app}"
 
 if [ ${FLAGS_letsencrypt} -eq ${FLAGS_TRUE} ]; then
